server:
  port: 8080

app:
  eureka-server: authorization

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411