server.port: 9999
server.forward-headers-strategy: framework

spring.application.name: authorization

jwt.publicKey: classpath:app.pub
# DO NOT Store private key in the Git Repository
# This is a sample application, and I added it only for demonstration purposes
jwt.privateKey: classpath:app.key

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411

logging:
  level:
    org.springframework.security: TRACE