server.port: 9999
server.forward-headers-strategy: framework

spring.application.name: authorization

app.eureka: localhost
app.zipkin: localhost
app.authorization: localhost

jwt.publicKey: classpath:app.pub
# DO NOT Store private key in the Git Repository
# This is a sample application, and I added it only for demonstration purposes
jwt.privateKey: classpath:app.key

eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka}:8761/eureka
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${app.zipkin}:9411

logging:
  level:
    org.springframework.security: TRACE