spring:
  kafka:
    bootstrap-servers: kafka:29092

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
