server:
  port: 8083

app.eureka: localhost
app.zipkin: localhost
app.authorization: localhost
app.mysql: localhost
app.kafka: localhost

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${app.kafka}:9092
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.programming.techie.OrderPlacedEvent
    template:
      default-topic: notificationTopic

eureka.client.serviceUrl.defaultZone: http://${app.eureka}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://${app.zipkin}:9411