server:
  port: 8083

app.eureka: localhost
app.zipkin: localhost
app.authorization: localhost
app.mysql: localhost
app.kafka: localhost

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: ${app.kafka}:9092
    consumer:
      group-id: notificationId
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            type:
              mapping: event:com.programming.techie.OrderPlacedEvent
    template:
      default-topic: notificationTopic

eureka.client.serviceUrl.defaultZone: http://${app.eureka}:8761/eureka

# WARNING: Exposing all management endpoints over http should only be used during development, must be locked down in production!
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.endpoint.health.probes.enabled: true
management.metrics.tags.application: ${spring.application.name}
management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
management.tracing.sampling.probability: 1.0