server:
  port: 8080

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://auth-server:9999

app:
  eureka-server: discovery-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411