apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-server
  name: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  strategy: {}
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
        - env:
            - name: LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY
              value: ' TRACE'
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          image: chensoul/auth-server:latest
          name: auth-server
          ports:
            - containerPort: 9999
            - containerPort: 9999
          resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth-server
  name: auth-server
spec:
  type: LoadBalancer
  ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
  selector:
    app: auth-server

