server:
  port: 9000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: oauth2-server
          uri: lb://authorization
          predicates:
            - Path=/oauth2/**

        - id: oauth2-login
          uri: lb://authorization
          predicates:
            - Path=/login/**

        - id: oauth2-error
          uri: lb://authorization
          predicates:
            - Path=/error/**

        - id: product-service
          predicates:
            - Path=/api/product
          uri: lb://product-service

        - id: order-service
          predicates:
            - Path=/api/order
          uri: lb://order-service

        - id: eureka-web
          predicates:
            - Path=/eureka/web
          uri: http://eureka:password@${app.eureka-server}:8761
          filters:
            - SetPath=/

        - id: eureka-static
          predicates:
            - Path=/eureka/**
          uri: http://eureka:password@${app.eureka-server}:8761

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://localhost:9999

app:
  eureka-server: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411

logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE