server:
  port: 9000

app.eureka: localhost
app.zipkin: localhost
app.authorization: localhost

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: oauth2-server
          uri: lb://authorization
          predicates:
            - Path=/oauth2/**

        - id: oauth2-login
          uri: lb://authorization
          predicates:
            - Path=/login/**

        - id: oauth2-error
          uri: lb://authorization
          predicates:
            - Path=/error/**

        - id: product-service
          predicates:
            - Path=/api/product
          uri: lb://product-service

        - id: order-service
          predicates:
            - Path=/api/order
          uri: lb://order-service

        - id: eureka-web
          predicates:
            - Path=/eureka/web
          uri: http://${app.eureka}:8761
          filters:
            - SetPath=/

        - id: eureka-static
          predicates:
            - Path=/eureka/**
          uri: http://${app.eureka}:8761

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://${app.authorization}:9999

eureka.client.serviceUrl.defaultZone: http://${app.eureka}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${app.zipkin}:9411

logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.security: TRACE
    org.springframework.web.server.adapter.HttpWebHandlerAdapter: TRACE