server:
  port: 8080

spring.security.oauth2.resourceserver.jwt.issuer-uri: http://authorization:9999

app:
  eureka-server: eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411