server:
  port: 8761

app.eureka: localhost
app.zipkin: localhost

spring:
  application:
    name: eureka
  security:
    user:
      name: eureka
      password: password

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${app.zipkin}:9411