server:
  port: 8084

spring:
  application:
    name: product-service
  data:
    mongodb:
      database: product-service
      host: localhost
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
management:
  endpoints:
    web:
      exposure:
        include: prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411