server:
  port: 8080

spring:
  data:
    mongodb:
      url: mongodb://root:password@mongodb:27017/product_service?authSource=admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
