server.port: 8080

app.eureka: localhost
app.zipkin: localhost
app.authorization: localhost
app.mysql: localhost
app.kafka: localhost
app.mongodb: localhost

spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:password@${app.mongodb}:27017/product_service?authSource=admin

eureka.client.serviceUrl.defaultZone: http://${app.eureka}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${app.zipkin}:9411