server.port: 8084

spring:
  application:
    name: product-service
  data:
    mongodb:
      host: localhost
      username: user
      password: pass
      database: microservices
      authentication-database: admin

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
management.endpoint.health.probes.enabled: true
management.metrics.tags.application: ${spring.application.name}

management.zipkin.tracing.endpoint: http://localhost:9411/api/v2/spans
management.tracing.sampling.probability: 1.0