server:
  port: 8082

app.eureka: localhost
app.zipkin: localhost
app.authorization: localhost
app.mysql: localhost

spring:
  application:
    name: inventory-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${app.mysql}:3306/inventory_service
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: none

eureka.client.serviceUrl.defaultZone: http://${app.eureka}:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${app.zipkin}:9411
