server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/inventory_service

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@eureka:8761/eureka
management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411
