---
apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin.default.svc.cluster.local:9411"
  SPRING_KAFKA_BOOTSTRAP-SERVERS: "kafka.default.svc.cluster.local:29092"